### ISSUE TITLE
BAD neighbour instantly added after removing

### ISSUE THREAD

**Issue by vivekmarakana** [bluedigits/nstats#2]
Hi, I'm using threshold 1 with 30000ms interval. I have one bad neighbor node. NSTATS add it back just after removing. See the log below:

```
NSTATS: Health of neighbor 'ABCD/XXX.XX.XXX.XXX:14265' became BAD. Going to remove... 
NSTATS: Successfully removed neighbor 'ABCD/XXX.XX.XXX.XXX:14265'.
NSTATS: Neighbor  'ABCD/XXX.XX.XXX.XXX:14265' seems to be available again. Going to add... 
NSTATS: Successfully added neighbor 'ABCD/XXX.XX.XXX.XXX:14265'.
```

I've masked the domain & IP, just FYI.

**Comment by bluedigits** [comment]
Hi Vivek,

Thank you for your message and sorry for the late reply. The behavior is due to the silly implementation of the neighbor availability check, which you can see in the code at https://github.com/bluedigits/nstats/blob/master/index.js#L138 ff where you can see that the check consists of nothing but a simple ping to the neighbor host machine.

This means, as long as the neighbor machine responds to those ping checks, it would always be considered as reachable. 

To get a more consistent neighbor availability check, the IOTA core team would have to implement this issue https://github.com/iotaledger/iri/issues/200

I hope this helps.
